export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const COMPLETE_TASK_REQUEST = 'COMPLETE_TASK_REQUEST';

export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const ADD_TASK = 'ADD_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';

export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';
export const COMPLETE_TASK_FAILURE = 'COMPLETE_TASK_FAILURE';